version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./app:/app
      - ./chroma_db:/app/chroma_db
    env_file:
      - .env
    restart: always

  chroma:
    image: chromadb/chroma
    volumes:
      - ./chroma_db:/chroma/chroma_db
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - PERSIST_DIRECTORY=/chroma/chroma_db
    ports:
      - "8000:8000"